hobbysite/merchstore/urls.py
"""Module providing a function redirecting urls to merch store."""

from django.urls import path
from .views import product_list, ProductDetail, product_create, ProductUpdate, cart, transactions
urlpatterns = [
    path('', product_list, name= 'items'),
    path('add', product_create, name= 'add'),
    path('<int:pk>/edit', ProductUpdate.as_view(), name= 'edit'),
    path('cart', cart, name= 'cart'),
    path('transactions', transactions, name= 'transactions'),
    path('<int:pk>', ProductDetail.as_view(), name = "item-detail"),
]
app_name = 'merchstore'

hobbysite/merchstore/templates/items/cart.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Merchandise Store{% endblock %}
{% block content %}
        <ul>
            <h1> Merchandise Store </h1>

            <h1> {{request.user.profile.name}}'s Cart </h1>
                
                {% for owner, transactions in owner_sort %}
                    <h2>{{ owner.user.username}}'s Products</h2>
                        {% for transaction in transactions %}
                            {% if user.profile != transaction.product.owner and user.profile == transaction.buyer %}
                                <li>Name of product: {{transaction.product.name}}</a>
                                <p>Product's current status:{{transaction.status}}</p>
                                <p>Amount of product to buy: {{transaction.amount}}</p>

                                <P>Price per product: {{transaction.product.price|floatformat:2}} Php
                                </li>  
                            {% endif %}
                        {% endfor %}   
                {% endfor %}
        </ul>
{% endblock %}

hobbysite/merchstore/templates/items/items.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Merchandise Store{% endblock %}
{% block content %}
        <ul>
            <h1> Merchandise Store </h1>
            {% if request.user.is_authenticated %}
                    <p><a href="{% url 'merchstore:cart' %}">{{request.user.profile.name}}'s Cart</a></p>

                    <p><a href="{% url 'merchstore:transactions' %}">{{request.user.profile.name}}'s Sold Products</a></p>
                    
            {% endif %}
            {% if request.user.is_authenticated %}
                <h1> {{request.user.profile.name}}'s Products </h1>
                {% for Product in user_products|dictsort:"name" %}
                    <li>Product: <a href="{{Product.get_absolute_url}}">{{Product.name}}</a>
                    <p>Status: {{Product.status}}</p>
                    </li>
                {% endfor %}    
            {% endif %}
            <h1> All Products </h1>
            {% for Product in products|dictsort:"name" %}
                {% if request.user.is_authenticated %}
                    {% if request.user != Product.owner.user %}
                        <li>Product: <a href="{{Product.get_absolute_url}}">{{Product.name}}</a>
                        <p>Status: {{Product.status}}</p>
                        </li>
                    {% endif %}
                {% else %}
                        <li>Product: <a href="{{Product.get_absolute_url}}">{{Product.name}}</a>
                        <p>Status: {{Product.status}}</p>
                        </li>
                {% endif %}        
            {% endfor %}
            
            <h2> Product Types available</h2>
            {% for product_type in product_types|dictsort:"name" %}
                <li>
                <p>{{product_type.name}}</p>
                <p>{{product_type.description}}</p>
                </li>
            {% endfor %}

            {% if request.user.is_authenticated %}
                    <li><a href="{% url 'merchstore:add' %}">Add Product</a>
                    </li>
            {% endif %}
        </ul>
{% endblock %}

hobbysite/merchstore/templates/items/transactions.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Merchandise Store{% endblock %}
{% block content %}
        <ul>
            <h1> Merchandise Store </h1>

            <h1> {{request.user.profile.name}}'s Transactions </h1>
                {% for buyer, transactions in buyer_sort %}
                    <h2>{{ buyer.user.username}}'s Purchases</h2>
                        {% for transaction in transactions %}
                            {% if user.profile != transaction.buyer %}
                                <li>Name of product: {{transaction.product.name}}</a>
                                <p>Product's current status: {{transaction.status}}</p>
                                <p>Amount of product being bought: {{transaction.amount}}</p>
                                <p>Price of product being bought: {{transaction.product.price}} Php</p>
                                </li>
                            {% endif %}  
                        {% endfor %}   
                {% endfor %}
        </ul>
{% endblock %}