hobbysite/commissions/urls.py
"""This file sets up the urls for the commissions app."""
from django.urls import path
from .views import CommissionListView, CommissionDetailView, CommissionCreateView, CommissionUpdateView

urlpatterns = [
    path('list', CommissionListView.as_view(), name='commissions-list'),
    path('detail/<int:pk>', CommissionDetailView.as_view(), name='commissions-detail'),
    path('add', CommissionCreateView.as_view(), name='commissions-create'),
    path('<int:pk>/edit', CommissionUpdateView.as_view(), name='commissions-update')
]

app_name = 'commissions'

hobbysite/commissions/models.py
"""This file sets up the models for the commissions app."""
from django.db import models
from django.urls import reverse
from datetime import datetime
from user_management.models import Profile


class Commission(models.Model):
    """Class for the Commission model for the commissions app."""

    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE, 
        related_name="commision",
        null=True
        )
    description = models.TextField()

    OPEN = "A"
    FULL = "B"
    COMPLETED = "C"
    DISCONTINUED = "D"
    
    COMMISSION_STATUS_CHOICES = {
        OPEN: "Open",
        FULL: "Full",
        COMPLETED: "Completed",
        DISCONTINUED: "Discontinued",
    }

    status = models.CharField(
        max_length=50,
        choices=COMMISSION_STATUS_CHOICES, 
        default=OPEN
        )
    created_on = models.DateTimeField(auto_now_add=True, null=False)
    updated_on = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('commissions:commissions-detail', args=[self.pk])

    class Meta:
        ordering = ['created_on']
        verbose_name = 'commission'
        verbose_name_plural = 'commissions'


class Job(models.Model):
    """Class for the Job model for the commissions app."""

    commission = models.ForeignKey(
        Commission,
        on_delete=models.CASCADE,
        related_name='job'
        )
    role = models.CharField(max_length=255)
    manpower_required = models.IntegerField()

    OPEN = "A"
    FULL = "B"
    
    JOB_STATUS_CHOICES = {
        OPEN: "Open",
        FULL: "Full",
    }

    status = models.CharField(
        max_length=50,
        choices=JOB_STATUS_CHOICES, 
        default=OPEN
        )
    
    def __str__(self):
        return self.role

    class Meta:
        ordering = ['status', '-manpower_required', 'role']
        verbose_name = 'job'
        verbose_name_plural = 'jobs'

class JobApplication(models.Model):
    """Class for the JobApplication model for the commissions app."""
    job = models.ForeignKey(
        Job, 
        on_delete=models.CASCADE, 
        related_name='jobapplication'
        )
    applicant = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE, 
        related_name='jobapplicant'
        )
    
    PENDING = "A"
    ACCEPTED = "B"
    REJECTED = "C"
    
    JOBAPPLICATION_STATUS_CHOICES = {
        PENDING: "Pending",
        ACCEPTED: "Accepted",
        REJECTED: "Rejected",
    }

    status = models.CharField(
        max_length=50,
        choices=JOBAPPLICATION_STATUS_CHOICES, 
        default=PENDING
        )
    applied_on = models.DateTimeField(auto_now_add=True, null=False)

    class Meta:
        ordering = ['status', 'applied_on']
        verbose_name = 'job application'
        verbose_name_plural = 'job applications'

hobbysite/commissions/templates/commission_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Create a New Commission {% endblock %}

{% block content %}
    <h3> Create a New Commission</h3>
    <p> Author of the Created Commission will be {{ user.profile.name }}</p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ commission_form.as_p }}
     <h3> Create a New Job </h3>
        {{ job_form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

hobbysite/commissions/templates/commission_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ commission.title }} {% endblock %}

{% block content %}
    <h2> {{ commission.title }} </h2>
    <p> {{ commission.description }}</p>
    <p> Author: {{ commission.author.name }}</p>
    <p> Status: {{ commission.get_status_display }}</p>
    <p> Created On: {{ commission.created_on }}</p>
    <p> Latest Update On: {{ commission.updated_on }}</p>
    <p> Total Manpower Required: {{ sum_manpower }}</p>
    <p> Open Manpower: {{ open_manpower }}</p>
    <b> JOBS </b>
    <ul>
        {% for job in commission.job.all %}
            <li>
                {{ job.role }} <br>
                Manpower Required: {{ job.manpower_required }} <br>
                Status: {{ job.get_status_display }}
                {% if user.is_authenticated %}
                    {% if job.get_status_display == 'Open' %}
                        <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" id="jobpk" name="jobpk" value='{{ job.pk }}'>
                            <button type="submit">Apply to Job</button>
                        </form>
                    {% endif %}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated %}
        {% if user.profile == commission.author %}
            <a href="{% url 'commissions:commissions-update' pk=commission.pk %}">Update Commission</a>
        {% endif %}
    {% endif %} 
    <br>
    <a href="{% url 'commissions:commissions-list' %}">Back to Commission List</a>
{% endblock %}

hobbysite/commissions/templates/commission_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Commissions List {% endblock %}

{% block content %}
    <h1>Commissions</h1>
    <a href="{% url 'commissions:commissions-create' %}">Create New Commission</a>
    {% if user.is_authenticated %}
        <h3> Authored Commissions </h3>
        <ul>
            {% for commission in object_list %}
                {% if user.profile == commission.author %}
                    <li><a href="{{ commission.get_absolute_url }}">{{ commission }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>

        <h3> Applied to Commissions </h3>
        <ul>
            {% for commission in object_list %}
                {% for job in commission.job.all %}
                    {% for jobapplication in job.jobapplication.all %}
                        {% if user.profile == jobapplication.applicant %}
                            <li><a href="{{ commission.get_absolute_url }}">{{ commission }}</a></li>
                        {% endif %}
                    {% endfor %}
                {% endfor %}

            {% endfor %}
        </ul>
    {% endif %}

    <h3> All Commissions </h3>
    <ul>
        {% for commission in object_list %}
            <li><a href="{{ commission.get_absolute_url }}">{{ commission }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

hobbysite/commissions/templates/commission_update.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Update {{ commission.title }} {% endblock %}

{% block content %}
    <h3> Update Commission {{ commission.title }}</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button name='commission-update' value="commission-update" type="submit">Submit</button>
    </form>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for job in commission.job.all %}
            <p>>Job: {{ job.role }}</p>
            <p>>Manpower Required: {{ job.manpower_required }}</p>
            {% for jobapplication in job.jobapplication.all %}
                {% if jobapplication.status == "A" %}
                <input type="hidden" id="japk" name="japk" value='{{ jobapplication.pk }}'>
                <p>Applicant: {{ jobapplication.applicant.name }}</p>
                <button name='applicant-accept' value="applicant-accept" type="submit">Accept</button> 
                <button name='applicant-reject' value="applicant-reject" type="submit">Reject</button>
                <br>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </form>


    <h4> Add Another Job </h4>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ job_form }}

        <button name='job-add' value="job-add" type="submit">Submit</button>
    </form>

{% endblock %}