hobbysite/blog/urls.py
from django.urls import path 
from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView

urlpatterns = [
    path('articles', ArticleListView.as_view() , name='article-list'), # URL for article list
    path('article/<int:pk>', ArticleDetailView.as_view() , name='article-detail'), # URL for article detail
    path('article/add', ArticleCreateView.as_view() , name='article-add'), # URL for adding new blogs
    path('article/<int:pk>/edit', ArticleUpdateView.as_view() , name='article-edit'), # URL for editings existing blogs
]

app_name = "blog"

hobbysite/forum/urls.py
"""This file defines the url path for each view."""
from django.urls import path 
from .views import ThreadListView, ThreadDetailView, ThreadCreateView, ThreadEditView

urlpatterns = [
    path('threads', ThreadListView.as_view() , name='thread-list'),
    path('thread/<int:pk>', ThreadDetailView.as_view() , name='thread-detail'),
    path('thread/add', ThreadCreateView.as_view(), name='thread-create'),
    path('thread/<int:pk>/edit', ThreadEditView.as_view(), name='thread-edit'),
]

app_name = "forum"

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('commissions/', include('commissions.urls', namespace = 'commissions')),
    path('blog/', include('blog.urls', namespace="blog")),
    path('wiki/', include('wiki.urls', namespace = 'wiki')),
    path('forum/', include('forum.urls', namespace="forum")),
    path('profile/', include('user_management.urls', namespace='profile')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls', namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/home/urls.py
from django.urls import path
from .views import HomepageTemplateView

urlpatterns = [

    path('', HomepageTemplateView.as_view(), name='homepage'),
    
]

app_name = "home"

hobbysite/merchstore/urls.py
"""Module providing a function redirecting urls to merch store."""

from django.urls import path
from .views import product_list, ProductDetail, product_create, ProductUpdate, cart, transactions
urlpatterns = [
    path('', product_list, name= 'items'),
    path('add', product_create, name= 'add'),
    path('<int:pk>/edit', ProductUpdate.as_view(), name= 'edit'),
    path('cart', cart, name= 'cart'),
    path('transactions', transactions, name= 'transactions'),
    path('<int:pk>', ProductDetail.as_view(), name = "item-detail"),
]
app_name = 'merchstore'

hobbysite/wiki/urls.py
"""This file sets up the urls for the wiki app."""
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView

urlpatterns = [

    path('articles/', ArticleListView.as_view(), name='list'), # URL for article list
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'), # URL for article detail
    path('article/add', ArticleCreateView.as_view() , name='add'), # URL for adding new articles
    path('article/<int:pk>/edit', ArticleUpdateView.as_view() , name='edit'), # URL for editing existing articles
    
]

app_name = "wiki"

hobbysite/templates/base.html
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %}Title{% endblock %}</title>
        {% block styles %}{% endblock %}
    </head>
    <header>
        <h1>Hobby Site</h1>
        {% if user.is_authenticated %}
            <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
            <br>
            <a href="{% url 'profile:profile-update' username=user.username%}">Update Profile</a>
        {% else %}
            <a href="{% url 'profile:profile-create' %}">Create a New User</a>
            <br>
            <a href="{% url 'login' %}">Login</a>
        {% endif %} 
        <br>
        <a href="{% url 'home:homepage' %}">Homepage</a>

        <h2>
            {% block header %}{% endblock %}
        </h2>
    </header>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

hobbysite/templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Hobby Site Homepage {% endblock %}

{% block header %}Welcome to the Hobby Site!{% endblock %}

{% block content %}
    <ul>
        <li><a href="{% url 'merchstore:items' %}">Merchstore</a></li>
        <li><a href="{% url 'wiki:list' %}">Online Wiki</a></li>
        <li><a href="{% url 'blog:article-list' %}">Blog</a></li>
        <li><a href="{% url 'forum:thread-list' %}">Forum</a></li>
        <li><a href="{% url 'commissions:commissions-list' %}">Commissions</a></li>
    </ul>
{% endblock %}