hobbysite/forum/urls.py
"""This file defines the url path for each view."""
from django.urls import path 
from .views import ThreadListView, ThreadDetailView, ThreadCreateView, ThreadEditView

urlpatterns = [
    path('threads', ThreadListView.as_view() , name='thread-list'),
    path('thread/<int:pk>', ThreadDetailView.as_view() , name='thread-detail'),
    path('thread/add', ThreadCreateView.as_view(), name='thread-create'),
    path('thread/<int:pk>/edit', ThreadEditView.as_view(), name='thread-edit'),
]

app_name = "forum"

hobbysite/forum/models.py
"""This file provides the base models for the forum app."""
from django.db import models
from django.urls import reverse
from user_management.models import Profile


class ThreadCategory(models.Model):
    """This class represents the thread's categories."""
    name = models.CharField(max_length=255)
    description = models.TextField(blank=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('thread-category-detail', args=[str(self.pk)])

    class Meta:    
        """This class uses metadata from the models import to arrange
        the categories in an ascending order based on name."""

        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        

class Thread(models.Model):
    """This class represents a thread, which contains categories."""
    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, 
        null=True, related_name="thread"
        )
    category = models.ForeignKey(
        ThreadCategory, on_delete=models.SET_NULL, 
        null=True, related_name="thread"
        )
    entry = models.TextField(blank=False)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True, null=False)
    updated_on = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:thread-detail', args=[str(self.pk)])

    class Meta:
        """This class uses metadata from the models import to arrange
        the threads in a descending order based on date created."""
        
        ordering = ['-created_on']
        verbose_name = 'thread'
        verbose_name_plural = 'threads'


class Comment(models.Model):
    "This class represents the comments that respond to a thread."
    author = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, 
        null=True, related_name="comment"
        )
    thread = models.ForeignKey(
        Thread, on_delete=models.CASCADE, 
        null=True, related_name="comment"
        )
    entry = models.TextField(blank=False)
    created_on = models.DateTimeField(auto_now_add=True, null=False)
    updated_on = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        if self.author and self.author.user:
            return f"{self.author.user.username}"

    def get_absolute_url(self):
        return reverse('comment-detail', args=[str(self.pk)])

    class Meta:
        """This class uses metadata from the models import to arrange
        the comments in an ascending order based on date created."""

        ordering = ['created_on']
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

hobbysite/forum/forms.py
"""This file defines the forms used by the different views."""
from django import forms
from .models import Comment, Thread

class CommentForm(forms.ModelForm):
    """Creates the form to be used by the model Comment"""
    
    class Meta:
        """This class uses metadata from the models 
        import to get the Comment form's fields."""
        model = Comment
        fields = ['entry']

from .models import Thread

class ThreadForm(forms.ModelForm):
    """Creates the form to be used by the create and add views"""
    
    class Meta:
        """This class uses metadata from the models 
        import to get the Thread form's fields."""
        model = Thread
        fields = ['title', 'category', 'entry', 'image']

hobbysite/forum/views.py
"""This file defines each view by referencing the models."""
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from .models import ThreadCategory, Thread, Comment, Profile
from .forms import CommentForm


class ThreadListView(TemplateView):
    """Views the posts' category."""

    model = ThreadCategory
    template_name = 'thread_list.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        
        if user.is_authenticated:
            profile = Profile.objects.get(user=user)
            user_threads = Thread.objects.filter(author=profile)
            all_threads = Thread.objects.exclude(author=profile)

        else:
            user_threads = Thread.objects.none()
            all_threads = Thread.objects.all()

        category_threads = {}

        for category in ThreadCategory.objects.all():
            threads_in_category = all_threads.filter(category=category)
            if threads_in_category.exists():
                category_threads[category] = threads_in_category
                
        ctx = {
            'user_threads': user_threads,
            'category_threads': category_threads,
        }

        return render(request, 'thread_list.html', ctx)


class ThreadDetailView(LoginRequiredMixin, DetailView):
    """Views the details of the thread of posts."""

    model = Thread
    template_name = 'thread_detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        thread = self.object
        category = thread.category
        
        ctx['other_threads'] = Thread.objects.filter(category=category).exclude(id=thread.id)[:2]
        ctx['comments'] = Comment.objects.filter(thread=thread).order_by('created_on')
        ctx['comment_form'] = CommentForm()
        return ctx

        return render(request, 'templates/thread_detail.html', ctx)

    def post(self, request, *args, **kwargs):
        thread = self.get_object()

        if not request.user.is_authenticated:
            return HttpResponseForbidden("You must be logged in to comment.")
        
        form = CommentForm(request.POST)
        if form.is_valid():
            c = form.save(commit=False)
            c.thread = thread
            c.author = Profile.objects.get(user=request.user)
            c.save()
            return redirect(thread.get_absolute_url())
        else:
            ctx = self.get_context_data()
            ctx['comment_form'] = form
            return self.render_to_response(ctx)


class ThreadCreateView(LoginRequiredMixin, CreateView):
    """Views the 'create a thread' page."""

    model = Thread
    template_name = 'thread_create.html'
    fields = ['title', 'category', 'entry', 'image']

    def get_queryset(self):
        return Thread.objects.filter(author__user=self.request.user)
    
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.author = profile
        return super().form_valid(form)

    def get_redirect_url(self):
        return reverse_lazy('thread-detail', kwargs={'pk': self.object.pk})


class ThreadEditView(LoginRequiredMixin, UpdateView):
    """Views the 'edit thread' page.""" 

    model = Thread
    template_name = 'thread_edit.html'
    fields = ['title', 'category', 'entry', 'image']

    def get_queryset(self):
        return Thread.objects.filter(author__user=self.request.user)

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.author = profile
        return super().form_valid(form)

    def get_redirect_url(self):
        return reverse_lazy('thread-detail', kwargs={'pk': self.object.pk})

hobbysite/forum/templates/thread_add.html
{% if user.is_authenticated %}
        

    {% else %}
        <p><b>Login to see this page.</b></p>    
    {% endif %}

hobbysite/forum/templates/thread_create.html
{% extends 'base.html' %}
{% load static %}

<title>Create a New Thread</title>

{% block content %}
    
{% if user.is_authenticated %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit">Post Thread</button>
    </form>

    <p><strong><a href="{% url 'forum:thread-list' %}">Go Back to Thread List</a><strong></p>
    
{% else %}
    <p>You must be logged in to post a thread.</p>

{% endif %}

{% endblock %}

hobbysite/forum/templates/thread_detail.html
<!-- This file formats the details of the thread of threads. -->

{% extends 'base.html' %}
{% load static %}

<title>Thread Info</title>

{% block content %} 

  <h2>By {{ thread.author.user.username }} on {{ thread.created_on }}</h2>

  <p>{{ thread.entry }}</p>
  {% if thread.image %}
    <img src="{{ thread.image.url }}" alt="{{ thread.title }}">
  {% endif %}
  
  <h3>Comments</h3>
  
  {% for comment in comments %}
    <div class="comment">
      <p><strong>{{ comment.author.user.username }}</strong></p> 
      <i>{{ comment.created_on }}</i>
      <p>{{ comment.entry }}</p>
    </div>
  {% empty %}
    <p>No comments... yet.</p>
  {% endfor %}
  
  {% if user.is_authenticated %}
    <h4>Leave a Comment:</h4>
    <form method="post">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit">Submit</button>
    </form>
  {% else %}
    <p>You must be logged in to comment.</p>
  {% endif %}
  
  {% if user.is_authenticated and user.profile == thread.author %}
    <a href="{% url 'forum:thread-edit' pk=thread.pk %}">Edit Thread</a>
  {% endif %}
  
  <h5>Other Threads in this Category:</h5>
  <ul>
    {% for other_thread in other_threads %}
      <li><a href="{% url 'forum:thread-detail' other_thread.id %}">{{ other_thread.title }}</a></li>
    {% empty %}
      <p>No other threads in this category.</p>
    {% endfor %}
  </ul>
  
  <p><strong><a href="{% url 'forum:thread-list' %}">Back to Thread List</a></strong></p>
  
{% endblock %}

hobbysite/forum/templates/thread_edit.html
{% extends 'base.html' %}
{% load static %}

<title>{% if object %}Edit Thread{% else %}Create Thread{% endif %}</title>

{% block content %}

{% if user.is_authenticated %}
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" value="{{ form.title.value }}">
        </div>

        <div>
            <label for="category">Category:</label>
            <select name="category" id="category">
                <option value="">Select Category</option>
                {% for category in form.category.field.queryset %}
                    <option value="{{ category.id }}" {% if category.id == form.category.value %}selected{% endif %}>
                        {{ category.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="id_entry">Post Entry:</label>
            <textarea name="entry" id="id_entry">{{ form.entry.value }}</textarea>
        </div>

        <div>
            <label for="id_image">Image (optional):</label>
            <input type="file" name="image" id="image">
        </div>

        <button type="submit">Update Thread</button>
    </form>

    <p><strong><a href="{% url 'forum:thread-list' %}">Go Back to Thread List</a></strong></p>

{% else %}
    <p><b>Login to see this page.</b></p>    
{% endif %}

{% endblock %}

hobbysite/forum/templates/thread_list.html
<!-- This file formats the threads as a thread with their corresponding links -->

{% extends 'base.html' %}
{% load static %}

<title>Thread List</title>

{% block content %} 

    {% if user.is_authenticated %}
        <h2>Your Threads</h2>
        {% if user_threads %}
            <ul>
            {% for thread in user_threads %}
                <li><a href="{{ thread.get_absolute_url }}">{{ thread.title }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>You have not created any threads.</p>
        {% endif %}
    {% else %}
        <p>Login to view your threads.</p>
    {% endif %}

    <h3>All Threads by Category</h3>
    {% for category, threads in category_threads.items %}
        <p><strong>{{ category.name }}</strong></p>
        <ul>
            {% for thread in threads %}
            <li><a href="{{ thread.get_absolute_url }}">{{ thread.title }}</a></li>
            {% endfor %}
        </ul>
    {% empty %}
        <p>No threads available.</p>
    {% endfor %}

    <p><strong><a href="{% url 'forum:thread-create' %}">Create a new thread?</a></strong></p>

{% endblock %}